In [1]:
import numpy as n

In [3]:
ar= n.array([1,2,3,4,5,6])
print (ar)

[1 2 3 4 5 6]


In [4]:
ar.shape

(6,)

In [5]:
a = n.array([[1,2,3],[1,2,3]])
print(a)

[[1 2 3]
 [1 2 3]]


In [7]:
arr = n.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(arr)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [14]:
arry = n.array([[[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
print(arry)

[[[[1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]]]]


In [11]:
arry.itemsize

4

In [12]:
arry.size

16

In [15]:
arry.shape

(1, 1, 4, 4)

In [22]:
arry = n.array([[[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]])
print(arry)
arry.size
arry.itemsize

[[[[1 2 3 4 5]
   [1 2 3 4 5]
   [1 2 3 4 5]
   [1 2 3 4 5]]]]


4

In [24]:
arry.size
arry.shape

(1, 1, 4, 5)

In [25]:
arry = n.array([[[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]])
arry.reshape(5,4)

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 5, 1, 2],
       [3, 4, 5, 1],
       [2, 3, 4, 5]])

In [29]:
arry = n.array([[[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]])
arry[1:,:3]

array([], shape=(0, 1, 4, 5), dtype=int32)

In [30]:
a = n.array([[1,2,3],[9,10,11]])
a[0,1]

2

In [31]:
a = n.array([[1,2,3],[9,10,11]])
a[0:,2]

array([ 3, 11])

In [33]:
a = n.array([[[1,2,3],[9,10,11],[4,5,6],[50,52,54]]])
a[0:,1]

array([[ 9, 10, 11]])

In [37]:
a = n.array([[1,3],[9,11],[4,6],[50,54]])
a[0:3,1]

array([ 3, 11,  6])

In [39]:
a = n.linspace(1,100,10)
a

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [40]:
a.min()

1.0

In [41]:
a.max()

100.0

In [42]:
a.sum()

505.0

In [43]:
a=n.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
a.shape

(2, 3)

In [45]:
a[0]

array([1, 2, 3])

In [46]:
a[0,0]

1

In [47]:
a.sum(axis=1)
#sum of row

array([ 6, 15])

In [48]:
a.sum(axis=0)
#sum of column

array([5, 7, 9])

In [52]:
a=n.array([[1,2,3],[4,5,6]])
n.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
x=n.array([[1,2,3],[4,5,6]])
y=n.array([[1,2,3],[4,5,6]])
x+y

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [54]:
x-y

array([[0, 0, 0],
       [0, 0, 0]])

In [55]:
x*y

array([[ 1,  4,  9],
       [16, 25, 36]])

In [56]:
x/y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
# vertical stacking
x=n.array([[1,2,3],[4,5,6]])
y=n.array([[1,2,3],[4,5,6]])
# concatenating two array
n.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
#horizontl stacking
x=n.array([[1,2,3],[4,5,6]])
y=n.array([[1,2,3],[4,5,6]])
n.hstack((x,y))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Pandas

## Operations

In [60]:
import pandas as pd

In [63]:
lst1 = ['a','b','c','d']
lst2 = [1,2,3,4]
pd.Series(lst1,index = lst2)

1    a
2    b
3    c
4    d
dtype: object

In [68]:
lst1 = ['a','b','c','d']
lst2 = [1,2,3,4]
pd.Series(lst1,index =lst2)

1    a
2    b
3    c
4    d
dtype: object

In [71]:
import numpy as n

In [74]:
lst1 = ['a','b','c','d']
lst2 = [1,2,3,4]
pd.Series(lst1,index =lst2)
arr = n.array(lst1)
print(arr)

['a' 'b' 'c' 'd']


In [75]:
pd.Series(lst1,index =lst2)

1    a
2    b
3    c
4    d
dtype: object

In [76]:
lst = ['a','b','c']
lst

['a', 'b', 'c']

In [77]:
lst_var = lst*2

In [78]:
lst_var

['a', 'b', 'c', 'a', 'b', 'c']

In [80]:
series = pd.Series(lst)

In [81]:
series

0    a
1    b
2    c
dtype: object

In [83]:
ser_var = series*3
ser_var

0    aaa
1    bbb
2    ccc
dtype: object

In [85]:
s1 = pd.Series([1,2],['Maths','English'])
s1

Maths      1
English    2
Hindi      3
dtype: int64

In [87]:
s2 = pd.Series([1,2],['Maths', 'Hindi'])
s2

Maths    1
Hindi    2
dtype: int64

In [88]:
s1+s2

English    NaN
Hindi      5.0
Maths      2.0
dtype: float64

# #Data Frame

In [3]:
import numpy as np
import pandas as pd
from numpy.random import randn
df = pd.DataFrame(np.random.randint(0,100,size = (5,5)),columns = list('ABCDE'))
df                

A   B   C   D   E
0  41  56  61  36  23
1  33   4  42  84  18
2  25  75  35  98  46
3  23  31  18  92  52
4  43  60  48  43  64

In [3]:
import numpy as np
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
a = np.array

In [13]:
import pandas as pd
webinfo = {'Day':[1,2,3,4,5,6,7,8],"Visitors":[108,543,229,390,893,2493,982,788],'Bounce Rate':[19,2,98,46,62,25,963,81]}
df = pd.DataFrame(webinfo)
print(df)

   Day  Visitors  Bounce Rate
0    1       108           19
1    2       543            2
2    3       229           98
3    4       390           46
4    5       893           62
5    6      2493           25
6    7       982          963
7    8       788           81


## Operations of Data Frame


1.Slicing DataFrame
2.Changing index 
3.Data Conversion
4.Joining and Merging
5.Concatenation
6.Changing column headers

### 1.Slicing

In [14]:
import pandas as pd
webinfo = {'Day':[1,2,3,4,5,6,7,8],"Visitors":[108,543,229,390,893,2493,982,788],'Bounce Rate':[19,2,98,46,62,25,963,81]}
df = pd.DataFrame(webinfo)
# prints the first set of row present in the dataset.
print(df.head(2))


   Day  Visitors  Bounce Rate
0    1       108           19
1    2       543            2


In [15]:
# prints the last set of row present in the dataset.
print(df.tail(2))

   Day  Visitors  Bounce Rate
6    7       982          963
7    8       788           81


In [19]:
scores  = {"Kholi":[239,434,293,108,349],"Dhoni":[319,174,213,135,189],"Yuvraj":[252,89,146,262,245],"Raina":[543,229,390,893,293],"Dhawan":[453,198,29,190,207]}
runs = {"Kholi":[239,434,293,108,349],"Dhoni":[319,174,213,135,189],"Yuvraj":[252,89,146,262,245],"Raina":[543,229,390,893,293],"Dhawan":[453,198,29,190,207]}
df1 = pd.DataFrame(scores)
df2 = pd.DataFrame(runs)
df1

Kholi  Dhoni  Yuvraj  Raina  Dhawan
0    239    319     252    543     453
1    434    174      89    229     198
2    293    213     146    390      29
3    108    135     262    893     190
4    349    189     245    293     207

In [20]:
df2

Kholi  Dhoni  Yuvraj  Raina  Dhawan
0    239    319     252    543     453
1    434    174      89    229     198
2    293    213     146    390      29
3    108    135     262    893     190
4    349    189     245    293     207

### Merging

In [23]:
df2 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"Ind_GDF":[50,45,54,67]},index = [2005,2006,2007,2008])

In [25]:
merge = pd.merge(df1,df2,on = "HPI")
merge

HPI  Int_Rate_x  Ind_GDF_x  Int_Rate_y  Ind_GDF_y
0   80           2         50           2         50
1   90           1         45           1         45
2   70           2         54           2         54
3   60           3         67           3         67

### Joining

In [26]:
df1 = pd.DataFrame({"Int_Rate":[2,1,2,3],"Ind_GDF":[50,45,54,67]},index = [2001,2002,2003,2004])
df2 = pd.DataFrame({"Low Tier HPI":[40,67,70,20],"Unemployment":[5,9,14,7]},index = [2001,2003,2004,2004])
joined = df1.join(df2)
joined

Int_Rate  Ind_GDF  Low Tier HPI  Unemployment
2001         2       50          40.0           5.0
2002         1       45           NaN           NaN
2003         2       54          67.0           9.0
2004         3       67          70.0          14.0
2004         3       67          20.0           7.0

### Changing index and column headers

In [27]:
df = pd.DataFrame({"Day": [1,2,3,4,5],"Visitors":[200,100,328,300,280],"Bounce Rate":[20,45,60,21,32]})

In [28]:
df

Day  Visitors  Bounce Rate
0    1       200           20
1    2       100           45
2    3       328           60
3    4       300           21
4    5       280           32

In [30]:
df.set_index("Day",inplace = True)

In [31]:
df

Visitors  Bounce Rate
Day                       
1         200           20
2         100           45
3         328           60
4         300           21
5         280           32

In [32]:
import matplotlib.pyplot as plt

In [33]:
from matplotlib import style

style.use("Five Thirty Eight")
df.plot()
plt.show()

In [36]:
df = df.rename(columns = {"Visitors":"Users"})

In [37]:
df

Users  Bounce Rate
Day                    
1      200           20
2      100           45
3      328           60
4      300           21
5      280           32

### Concatenation

In [38]:
df1 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"Ind_GDF":[50,45,54,67]},index = [2001,2002,2003,2004])
df2 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"Ind_GDF":[50,45,54,67]},index = [2005,2006,2007,2008])

In [40]:
concat = pd.concat([df1,df2])
concat

HPI  Int_Rate  Ind_GDF
2001   80         2       50
2002   90         1       45
2003   70         2       54
2004   60         3       67
2005   80         2       50
2006   90         1       45
2007   70         2       54
2008   60         3       67

### Data Munging

In [8]:
import pandas as pd
!cd

C:\Users\kasir\anaconda3


In [9]:
a = pd.read_csv("COVID-19 Cases.csv")

In [10]:
a

Date Country_Region Province_State  Case_Type  Cases  Confirmed  \
0      23-01-2020             US          Idaho  Confirmed      0        NaN   
1      23-01-2020             US          Idaho     Deaths      0        NaN   
2      23-01-2020             US         Oregon     Deaths      0        NaN   
3      23-01-2020             US         Oregon  Confirmed      0        NaN   
4      23-01-2020             US       Oklahoma  Confirmed      0        NaN   
...           ...            ...            ...        ...    ...        ...   
36455  24-03-2020        Georgia            NaN  Confirmed     70        NaN   
36456  24-03-2020          China          Macau  Confirmed     25        NaN   
36457  24-03-2020         Canada        Ontario  Confirmed    588        NaN   
36458  24-03-2020       Djibouti            NaN     Deaths      0        NaN   
36459  24-03-2020       Djibouti            NaN  Confirmed      3        NaN   

       Deaths   Difference  Table Names       Lat       Long  
0          NaN           0  Time Series  44.24050 -114.47880  
1          NaN           0  Time Series  44.24050 -114.47880  
2          NaN           0  Time Series  44.31683 -122.15308  
3          NaN           0  Time Series  44.31683 -122.15308  
4          NaN           0  Time Series  35.86230  -96.43495  
...        ...         ...          ...       ...        ...  
36455      NaN           9  Time Series  42.31540   43.35690  
36456      NaN           1  Time Series  22.16670  113.55000  
36457      NaN          85  Time Series  51.25380  -85.32320  
36458      NaN           0  Time Series  11.82510   42.59030  
36459      NaN           0  Time Series  11.82510   42.59030  

[36460 rows x 11 columns]

In [11]:
a.to_html("Corona Virus Data")

In [3]:
fraud.to_html('edu.html')

NameError: name 'fraud' is not defined

In [16]:
!cd

C:\Users\kasir\anaconda3


In [12]:
import pandas as pd
pd.read_csv("creditcard.csv")

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [17]:
!cd

C:\Users\kasir\anaconda3


In [19]:
import pandas as pd
s = pd.read_csv("SalesJan2009.csv")
print(s.head())

  Transaction_date   Product Price Payment_Type               Name  \
0      1/2/09 6:17  Product1  1200   Mastercard           carolina   
1      1/2/09 4:53  Product1  1200         Visa             Betina   
2     1/2/09 13:08  Product1  1200   Mastercard  Federica e Andrea   
3     1/3/09 14:44  Product1  1200         Visa              Gouya   
4     1/4/09 12:56  Product2  3600         Visa            Gerd W    

                           City     State         Country Account_Created  \
0                      Basildon   England  United Kingdom     1/2/09 6:00   
1  Parkville                           MO   United States     1/2/09 4:42   
2  Astoria                             OR   United States    1/1/09 16:21   
3                        Echuca  Victoria       Australia   9/25/05 21:13   
4  Cahaba Heights                      AL   United States  11/15/08 15:47   

     Last_Login   Latitude   Longitude  
0   1/2/09 6:08  51.500000   -1.116667  
1   1/2/09 7:49  39.195000  -94.68

In [2]:
import pandas as pd
s = pd.read_csv("C:\\Users\\kasir\\anaconda3\\SalesJan2009.csv")
print(s.head(2))

  Transaction_date   Product Price Payment_Type      Name  \
0      1/2/09 6:17  Product1  1200   Mastercard  carolina   
1      1/2/09 4:53  Product1  1200         Visa    Betina   

                           City    State         Country Account_Created  \
0                      Basildon  England  United Kingdom     1/2/09 6:00   
1  Parkville                          MO   United States     1/2/09 4:42   

    Last_Login  Latitude  Longitude  
0  1/2/09 6:08    51.500  -1.116667  
1  1/2/09 7:49    39.195 -94.681940  


In [3]:
import pandas as pd
s = pd.read_csv("C:\\Users\\kasir\\anaconda3\\SalesJan2009.csv",index_col = 0)
print(s.head(2))

                   Product Price Payment_Type      Name  \
Transaction_date                                          
1/2/09 6:17       Product1  1200   Mastercard  carolina   
1/2/09 4:53       Product1  1200         Visa    Betina   

                                          City    State         Country  \
Transaction_date                                                          
1/2/09 6:17                           Basildon  England  United Kingdom   
1/2/09 4:53       Parkville                          MO   United States   

                 Account_Created   Last_Login  Latitude  Longitude  
Transaction_date                                                    
1/2/09 6:17          1/2/09 6:00  1/2/09 6:08    51.500  -1.116667  
1/2/09 4:53          1/2/09 4:42  1/2/09 7:49    39.195 -94.681940  


#### Data Munjing Example

In [4]:
#converts the csv file to html and stores it in th same location
s.to_html("edu.html")

In [24]:
!cd

C:\Users\kasir\anaconda3


In [28]:
a = pd.read_csv("SacramentocrimeJanuary2006.csv")
print(a.head(2))

     cdatetime              address  district        beat  grid  \
0  1/1/06 0:00   3108 OCCIDENTAL DR         3  3C          1115   
1  1/1/06 0:00  2082 EXPEDITION WAY         5  5A          1512   

                      crimedescr  ucr_ncic_code   latitude   longitude  
0  10851(A)VC TAKE VEH W/O OWNER           2404  38.550420 -121.391416  
1     459 PC  BURGLARY RESIDENCE           2204  38.473501 -121.490186  


In a dataset that invovles data of many countries along with their unemployment rate from 2010 to 2015, we need to find out 
the change in % of unemployment rate  from 2010 to 2011.
variable = pd.read_csv("FileName.csv")
df = variable.head()
df = df.set_index (["Country Code"])
sd = df.reindex(columns['2010','2011'])
sb = sd.diff(axis= 1)
db.plot(kind='bar')
plt.show()

In [31]:
!cd

C:\Users\kasir\anaconda3


In [7]:
from statistics import mean
print (mean([1,2,3,4,5,6,7,8,9,10]))

5.5


from statistics import mean
from statistics import mode
from statistics import median
from statistics import variance

In [2]:
import sqlite3

In [12]:
import pandas as pd
!cd

C:\Users\kasir\anaconda3


# Movie Rating Data

In [1]:
import pandas as pd
!cd
movie = pd.read_csv("IMDB-Movie-Data.csv")

C:\Users\kasir\anaconda3


In [4]:
#reads the file from the destination and displays it.
movie = pd.read_csv("IMDB-Movie-Data.csv",index_col='Title')
movie

Rank                     Genre  \
Title                                                     
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi   
Prometheus                  2  Adventure,Mystery,Sci-Fi   
Split                       3           Horror,Thriller   
Sing                        4   Animation,Comedy,Family   
Suicide Squad               5  Action,Adventure,Fantasy   
...                       ...                       ...   
Secret in Their Eyes      996       Crime,Drama,Mystery   
Hostel: Part II           997                    Horror   
Step Up 2: The Streets    998       Drama,Music,Romance   
Search Party              999          Adventure,Comedy   
Nine Lives               1000     Comedy,Family,Fantasy   

                                                               Description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   
...                                                                    ...   
Secret in Their Eyes     A tight-knit team of rising investigators, alo...   
Hostel: Part II          Three American college students studying abroa...   
Step Up 2: The Streets   Romantic sparks occur between two dance studen...   
Search Party             A pair of friends embark on a mission to reuni...   
Nine Lives               A stuffy businessman finds himself trapped ins...   

                                     Director  \
Title                                           
Guardians of the Galaxy            James Gunn   
Prometheus                       Ridley Scott   
Split                      M. Night Shyamalan   
Sing                     Christophe Lourdelet   
Suicide Squad                      David Ayer   
...                                       ...   
Secret in Their Eyes                Billy Ray   
Hostel: Part II                      Eli Roth   
Step Up 2: The Streets             Jon M. Chu   
Search Party                   Scot Armstrong   
Nine Lives                   Barry Sonnenfeld   

                                                                    Actors  \
Title                                                                        
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...   
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...   
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...   
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...   
...                                                                    ...   
Secret in Their Eyes     Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...   
Hostel: Part II          Lauren German, Heather Matarazzo, Bijou Philli...   
Step Up 2: The Streets   Robert Hoffman, Briana Evigan, Cassie Ventura,...   
Search Party             Adam Pally, T.J. Miller, Thomas Middleditch,Sh...   
Nine Lives               Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...   

                         Year  Runtime (Minutes)  Rating   Votes  \
Title                                                              
Guardians of the Galaxy  2014                121     8.1  757074   
Prometheus               2012                124     7.0  485820   
Split                    2016                117     7.3  157606   
Sing                     2016                108     7.2   60545   
Suicide Squad            2016                123     6.2  393727   
...                       ...                ...     ...     ...   
Secret in Their Eyes     2015                

In [5]:
#displays the first 10 rows of information from the file.
movie.head(10)

Rank                       Genre  \
Title                                                       
Guardians of the Galaxy     1     Action,Adventure,Sci-Fi   
Prometheus                  2    Adventure,Mystery,Sci-Fi   
Split                       3             Horror,Thriller   
Sing                        4     Animation,Comedy,Family   
Suicide Squad               5    Action,Adventure,Fantasy   
The Great Wall              6    Action,Adventure,Fantasy   
La La Land                  7          Comedy,Drama,Music   
Mindhorn                    8                      Comedy   
The Lost City of Z          9  Action,Adventure,Biography   
Passengers                 10     Adventure,Drama,Romance   

                                                               Description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   
The Great Wall           European mercenaries searching for black powde...   
La La Land               A jazz pianist falls for an aspiring actress i...   
Mindhorn                 A has-been actor best known for playing the ti...   
The Lost City of Z       A true-life drama, centering on British explor...   
Passengers               A spacecraft traveling to a distant colony pla...   

                                     Director  \
Title                                           
Guardians of the Galaxy            James Gunn   
Prometheus                       Ridley Scott   
Split                      M. Night Shyamalan   
Sing                     Christophe Lourdelet   
Suicide Squad                      David Ayer   
The Great Wall                    Yimou Zhang   
La La Land                    Damien Chazelle   
Mindhorn                           Sean Foley   
The Lost City of Z                 James Gray   
Passengers                      Morten Tyldum   

                                                                    Actors  \
Title                                                                        
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...   
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...   
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...   
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...   
The Great Wall               Matt Damon, Tian Jing, Willem Dafoe, Andy Lau   
La La Land               Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....   
Mindhorn                 Essie Davis, Andrea Riseborough, Julian Barrat...   
The Lost City of Z       Charlie Hunnam, Robert Pattinson, Sienna Mille...   
Passengers               Jennifer Lawrence, Chris Pratt, Michael Sheen,...   

                         Year  Runtime (Minutes)  Rating   Votes  \
Title                                                              
Guardians of the Galaxy  2014                121     8.1  757074   
Prometheus               2012                124     7.0  485820   
Split                    2016                117     7.3  157606   
Sing                     2016                108     7.2   60545   
Suicide Squad            2016                123     6.2  393727   
The Great Wall           2016                103     6.1   56036   
La La Land               2016                128     8.3  258682   
Mindhorn                 2016                 89     6.4    2490   
The Lost City of Z       2016                141     7.1    7188   
Passengers               2016                116     7.0  192177   

            

In [6]:
#gives the dimension of matrix 
movie.shape

(1000, 11)

In [7]:
movie.tail(5)

Rank                  Genre  \
Title                                                 
Secret in Their Eyes     996    Crime,Drama,Mystery   
Hostel: Part II          997                 Horror   
Step Up 2: The Streets   998    Drama,Music,Romance   
Search Party             999       Adventure,Comedy   
Nine Lives              1000  Comedy,Family,Fantasy   

                                                              Description  \
Title                                                                       
Secret in Their Eyes    A tight-knit team of rising investigators, alo...   
Hostel: Part II         Three American college students studying abroa...   
Step Up 2: The Streets  Romantic sparks occur between two dance studen...   
Search Party            A pair of friends embark on a mission to reuni...   
Nine Lives              A stuffy businessman finds himself trapped ins...   

                                Director  \
Title                                      
Secret in Their Eyes           Billy Ray   
Hostel: Part II                 Eli Roth   
Step Up 2: The Streets        Jon M. Chu   
Search Party              Scot Armstrong   
Nine Lives              Barry Sonnenfeld   

                                                                   Actors  \
Title                                                                       
Secret in Their Eyes    Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...   
Hostel: Part II         Lauren German, Heather Matarazzo, Bijou Philli...   
Step Up 2: The Streets  Robert Hoffman, Briana Evigan, Cassie Ventura,...   
Search Party            Adam Pally, T.J. Miller, Thomas Middleditch,Sh...   
Nine Lives              Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...   

                        Year  Runtime (Minutes)  Rating  Votes  \
Title                                                            
Secret in Their Eyes    2015                111     6.2  27585   
Hostel: Part II         2007                 94     5.5  73152   
Step Up 2: The Streets  2008                 98     6.2  70699   
Search Party            2014                 93     5.6   4881   
Nine Lives              2016                 87     5.3  12435   

                        Revenue (Millions)  Metascore  
Title                                                  
Secret in Their Eyes                   NaN       45.0  
Hostel: Part II                      17.54       46.0  
Step Up 2: The Streets               58.01       50.0  
Search Party                           NaN       22.0  
Nine Lives                           19.64       11.0

In [8]:
#displays the title of  movies along with the genre .
movie['Genre']

Title
Guardians of the Galaxy     Action,Adventure,Sci-Fi
Prometheus                 Adventure,Mystery,Sci-Fi
Split                               Horror,Thriller
Sing                        Animation,Comedy,Family
Suicide Squad              Action,Adventure,Fantasy
                                     ...           
Secret in Their Eyes            Crime,Drama,Mystery
Hostel: Part II                              Horror
Step Up 2: The Streets          Drama,Music,Romance
Search Party                       Adventure,Comedy
Nine Lives                    Comedy,Family,Fantasy
Name: Genre, Length: 1000, dtype: object

In [9]:
#gives the information on each columns with its count and data type.
movie.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Genre               1000 non-null   object 
 2   Description         1000 non-null   object 
 3   Director            1000 non-null   object 
 4   Actors              1000 non-null   object 
 5   Year                1000 non-null   int64  
 6   Runtime (Minutes)   1000 non-null   int64  
 7   Rating              1000 non-null   float64
 8   Votes               1000 non-null   int64  
 9   Revenue (Millions)  872 non-null    float64
 10  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 133.8+ KB


In [2]:
#dispalys the titile of all the columns present in dataset.
movie.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [3]:
#shows the dataset of first column with all other columns seperately.
duplicate = movie.append(movie)
print(duplicate)

     Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley 

In [6]:
duplicate.loc[duplicate["Rank"] == 1000]

Rank       Title                  Genre  \
999  1000  Nine Lives  Comedy,Family,Fantasy   
999  1000  Nine Lives  Comedy,Family,Fantasy   

                                           Description          Director  \
999  A stuffy businessman finds himself trapped ins...  Barry Sonnenfeld   
999  A stuffy businessman finds himself trapped ins...  Barry Sonnenfeld   

                                                Actors  Year  \
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating  Votes  Revenue (Millions)  Metascore  
999                 87     5.3  12435               19.64       11.0  
999                 87     5.3  12435               19.64       11.0

In [8]:
movie_copy = movie

In [9]:
movie_copy ['Rank'] == range(1000,2000,1)

0      False
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Name: Rank, Length: 1000, dtype: bool

In [10]:
duplicate.drop_duplicates(inplace = True)
duplicate.shape

(1000, 12)

In [11]:
duplicate.drop_duplicates(inplace = False)
duplicate.shape

(1000, 12)

In [12]:
duplicate.drop_duplicates(subset = 'Genre',inplace = True)

In [14]:
duplicate.drop_duplicates(inplace = True, keep = False)

In [15]:
duplicate.shape

(207, 12)

In [20]:
movie.rename(columns = {
    "Description": "Des",
    "Revenue(Millions)":"Rev(M)"
},inplace = True)

In [21]:
movie

Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                                   Des              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley Scott   
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4    A secret government agency recruits some of th...            David Ayer   
..                                                 ...                   ...   
995  A tight-knit team of rising investigators, alo...             Billy Ray   
996  Three American college students studying abroa...              Eli Roth   
997  Romantic sparks occur between two dance studen...            Jon M. Chu   
998  A pair of friends embark on a mission to reuni...        Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012   
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016   
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
..                                                 ...   ...   
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
1                  124     7.0  485820              126.46       65.0  
2                  117     7.3  157606              138.12       62.0  
3                  108     7.2   60545              270.32       59.0  
4                  123     6.2  393727              325.02       40.0  
..                 ...     ...     ...                 ...        ...  
995                111     6.2   27585                 NaN       45.0  
996                 94     5.5   73152               17.54       46.0  
997                 98     6.2   70699               58.01       50.0  
998                 93     5.6    4881                 NaN       22.0  
999                 87     5.3   12435               19.64       11.0  

[1000 rows x 12 columns]

In [22]:
for i in movie:
    print(i)

Rank
Title
Genre
Des
Director
Actors
Year
Runtime (Minutes)
Rating
Votes
Revenue (Millions)
Metascore


In [28]:
movie.isna().sum()

Rank                    0
Title                   0
Genre                   0
Des                     0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [33]:
movie['Year']

0      2014
1      2012
2      2016
3      2016
4      2016
       ... 
995    2015
996    2007
997    2008
998    2014
999    2016
Name: Year, Length: 1000, dtype: int64

In [34]:
movie.corr()

Rank      Year  Runtime (Minutes)    Rating     Votes  \
Rank                1.000000 -0.261605          -0.221739 -0.219555 -0.283876   
Year               -0.261605  1.000000          -0.164900 -0.211219 -0.411904   
Runtime (Minutes)  -0.221739 -0.164900           1.000000  0.392214  0.407062   
Rating             -0.219555 -0.211219           0.392214  1.000000  0.511537   
Votes              -0.283876 -0.411904           0.407062  0.511537  1.000000   
Revenue (Millions) -0.271592 -0.126790           0.267953  0.217654  0.639661   
Metascore          -0.191869 -0.079305           0.211978  0.631897  0.325684   

                    Revenue (Millions)  Metascore  
Rank                         -0.271592  -0.191869  
Year                         -0.126790  -0.079305  
Runtime (Minutes)             0.267953   0.211978  
Rating                        0.217654   0.631897  
Votes                         0.639661   0.325684  
Revenue (Millions)            1.000000   0.142397  
Metascore                     0.142397   1.000000